corrected dockerhub name

diff --git a/.github/workflows/api-test.yaml b/.github/workflows/api-test.yaml
--- a/.github/workflows/api-test.yaml
+++ b/.github/workflows/api-test.yaml
@@ -36,6 +36,13 @@ jobs:
           mkdir -p $HOME/.kube
           echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config
 
+      - name: Debug kubeconfig
+        run: |
+          echo "Kubeconfig file exists?"
+          ls -l $HOME/.kube
+          echo "----- KUBECONFIG CONTENT -----"
+          cat $HOME/.kube/config || echo "config missing!"
+
       - name: Apply Kubernetes Job
         run: |
           kubectl apply -f k8s/k8s-test-job.yaml
